//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumoTC.ServicioTipoCambio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.bcn.gob.ni/", ConfigurationName="ServicioTipoCambio.Tipo_Cambio_BCNSoap")]
    public interface Tipo_Cambio_BCNSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.bcn.gob.ni/RecuperaTC_Dia", ReplyAction="*")]
        double RecuperaTC_Dia(int Ano, int Mes, int Dia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.bcn.gob.ni/RecuperaTC_Dia", ReplyAction="*")]
        System.Threading.Tasks.Task<double> RecuperaTC_DiaAsync(int Ano, int Mes, int Dia);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RecuperaTC_MesResult del espacio de nombres http://servicios.bcn.gob.ni/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.bcn.gob.ni/RecuperaTC_Mes", ReplyAction="*")]
        ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponse RecuperaTC_Mes(ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.bcn.gob.ni/RecuperaTC_Mes", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponse> RecuperaTC_MesAsync(ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaTC_MesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaTC_Mes", Namespace="http://servicios.bcn.gob.ni/", Order=0)]
        public ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequestBody Body;
        
        public RecuperaTC_MesRequest() {
        }
        
        public RecuperaTC_MesRequest(ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios.bcn.gob.ni/")]
    public partial class RecuperaTC_MesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Ano;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Mes;
        
        public RecuperaTC_MesRequestBody() {
        }
        
        public RecuperaTC_MesRequestBody(int Ano, int Mes) {
            this.Ano = Ano;
            this.Mes = Mes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecuperaTC_MesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecuperaTC_MesResponse", Namespace="http://servicios.bcn.gob.ni/", Order=0)]
        public ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponseBody Body;
        
        public RecuperaTC_MesResponse() {
        }
        
        public RecuperaTC_MesResponse(ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://servicios.bcn.gob.ni/")]
    public partial class RecuperaTC_MesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement RecuperaTC_MesResult;
        
        public RecuperaTC_MesResponseBody() {
        }
        
        public RecuperaTC_MesResponseBody(System.Xml.Linq.XElement RecuperaTC_MesResult) {
            this.RecuperaTC_MesResult = RecuperaTC_MesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Tipo_Cambio_BCNSoapChannel : ConsumoTC.ServicioTipoCambio.Tipo_Cambio_BCNSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Tipo_Cambio_BCNSoapClient : System.ServiceModel.ClientBase<ConsumoTC.ServicioTipoCambio.Tipo_Cambio_BCNSoap>, ConsumoTC.ServicioTipoCambio.Tipo_Cambio_BCNSoap {
        
        public Tipo_Cambio_BCNSoapClient() {
        }
        
        public Tipo_Cambio_BCNSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Tipo_Cambio_BCNSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Tipo_Cambio_BCNSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Tipo_Cambio_BCNSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double RecuperaTC_Dia(int Ano, int Mes, int Dia) {
            return base.Channel.RecuperaTC_Dia(Ano, Mes, Dia);
        }
        
        public System.Threading.Tasks.Task<double> RecuperaTC_DiaAsync(int Ano, int Mes, int Dia) {
            return base.Channel.RecuperaTC_DiaAsync(Ano, Mes, Dia);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponse ConsumoTC.ServicioTipoCambio.Tipo_Cambio_BCNSoap.RecuperaTC_Mes(ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest request) {
            return base.Channel.RecuperaTC_Mes(request);
        }
        
        public System.Xml.Linq.XElement RecuperaTC_Mes(int Ano, int Mes) {
            ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest inValue = new ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest();
            inValue.Body = new ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequestBody();
            inValue.Body.Ano = Ano;
            inValue.Body.Mes = Mes;
            ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponse retVal = ((ConsumoTC.ServicioTipoCambio.Tipo_Cambio_BCNSoap)(this)).RecuperaTC_Mes(inValue);
            return retVal.Body.RecuperaTC_MesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponse> ConsumoTC.ServicioTipoCambio.Tipo_Cambio_BCNSoap.RecuperaTC_MesAsync(ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest request) {
            return base.Channel.RecuperaTC_MesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumoTC.ServicioTipoCambio.RecuperaTC_MesResponse> RecuperaTC_MesAsync(int Ano, int Mes) {
            ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest inValue = new ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequest();
            inValue.Body = new ConsumoTC.ServicioTipoCambio.RecuperaTC_MesRequestBody();
            inValue.Body.Ano = Ano;
            inValue.Body.Mes = Mes;
            return ((ConsumoTC.ServicioTipoCambio.Tipo_Cambio_BCNSoap)(this)).RecuperaTC_MesAsync(inValue);
        }
    }
}
